# cloudbuild.yaml
# Pipeline de CI/CD para o MealIA no Google Cloud Platform

steps:
  # Passo 1: Build da imagem do Backend (FastAPI)
  - id: 'build-backend' # Adicionando IDs para clareza
    name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/mealia-backend/backend:$BUILD_ID',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/mealia-backend/backend:latest',
      './backend'
    ]

  # Passo 2: Push da imagem para Artifact Registry
  - id: 'push-backend'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'us-central1-docker.pkg.dev/$PROJECT_ID/mealia-backend/backend']
    waitFor: ['build-backend'] # Espera o passo anterior ser concluído

  # Passo 3: Deploy no Cloud Run (Otimizado para Free Tier)
  - id: 'deploy-backend'
    name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'mealia-backend',
      '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/mealia-backend/backend:$BUILD_ID',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--allow-unauthenticated',
      '--port', '8000',
      '--memory', '256Mi',
      '--cpu', '0.5',
      '--min-instances', '0',
      '--max-instances', '3',
      '--set-env-vars', 'ENVIRONMENT=production'
    ]
    waitFor: ['push-backend'] # Espera o push do backend ser concluído

  # Passo 4: Build e Deploy do Frontend
  - id: 'build-and-deploy-frontend'
    name: 'node:22'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd frontend
        npm install
        npm run build
        npm install -g firebase-tools
        cd ..
        firebase deploy --only hosting --project meal-ai-development-c1604 
    secretEnv: ['FIREBASE_TOKEN']
    waitFor: ['-']
      # O waitFor: ['-'] indica que este passo pode ser executado em paralelo com outros passos, se necessário.



# Configurações do build (Otimizado para Free Tier)
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '300s' # 5 minutos. Pode ser pouco se os builds forem longos. Ajuste se necessário.

substitutions:
  _REGION: 'us-central1' # Esta substituição não está sendo usada no seu YAML, mas pode ser útil para futuras expansões.

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/firebase-token/versions/latest
    env: 'FIREBASE_TOKEN'
    # Certifique-se de que o segredo 'firebase-token' existe no Secret Manager do GCP.
