# cloudbuild.yaml
# Pipeline de CI/CD para o MealIA no Google Cloud Platform

steps:
  # Passo 1: Build da imagem do Backend (FastAPI)
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/mealia-backend:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/mealia-backend:latest',
      '--build-arg', 'ENVIRONMENT=production',
      './backend'
    ]

  # Passo 2: Push da imagem para Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/mealia-backend']

  # Passo 3: Deploy no Cloud Run (Otimizado para Free Tier)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'mealia-backend',
      '--image', 'gcr.io/$PROJECT_ID/mealia-backend:$BUILD_ID',
      '--platform', 'managed',
      '--region', 'us-east1',  # Região com Free Tier mais generoso
      '--allow-unauthenticated',
      '--port', '8000',
      '--memory', '256Mi',      # Reduzido para ficar no Free Tier
      '--cpu', '0.5',          # CPU mínima (mais barata)
      '--min-instances', '0',   # Escala para zero (sem custo quando não usado)
      '--max-instances', '3',   # Limite baixo
      '--concurrency', '80',    # Otimiza uso de recursos
      '--set-env-vars', 'ENVIRONMENT=production'
    ]

  # Passo 4: Build do Frontend (React)
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd frontend
        npm install
        npm run build
        echo "Frontend build concluído!"


# Passo 5: Deploy no Firebase Hosting
#  - name: 'gcr.io/$PROJECT_ID/firebase'
#    args: [
#      'deploy',
#      '--only', 'hosting',
#      '--project', '$PROJECT_ID'
#    ]

# Configurações do build (Otimizado para Free Tier)
options:
  # Máquina padrão (gratuita nos primeiros 120 build-minutes/dia)
  machineType: 'E2_HIGHCPU_8'
  # Logs básicos para economizar
  logging: CLOUD_LOGGING_ONLY

# Timeout reduzido para economizar build-minutes
timeout: '300s'

# Substitições de variáveis  
substitutions:
  _REGION: 'us-east1'  # Região mais econômica